Hw09
EvgeniaLeleo/sky-react pull request #10
Opened 2022-06-18 18:02 UTC by EvgeniaLeleo

Задание 

- Взять компонент  `<MinMax>` с финального примера урока и сделать ленивым, то есть вызывать `callback` onChange не сразу, а при потере фокуса с `input` или нажатии key enter.
- В отдельном компоненте реализовать задачу:
    
    Дан `<select>` и 3 абзаца. Любой текст на ваш вкус. В селекте можно выбрать один из трех пунктов. Сделайте так, чтобы в зависимости от выбора на экране был виден один из трех абзацев.
    
- На формах `<input>` в компоненте LoginPass написать валидацию на корректность введенного email в поле логин(наличие @, домена, .com), и на введеный пароль, который должен быть не менее 6 символов.

2022-06-19 14:44 UTC, mrerberg requested changes

2022-06-19 14:44 UTC, mrerberg commented on src/components/utils.js
> +const isValidEmail = (string) => {
может аргумент тогда название email?

2022-06-19 16:05 UTC, EvgeniaLeleo commented on src/components/utils.js
> +const isValidEmail = (string) => {
Done

2022-06-20 07:26 UTC, mrerberg approved these changes

2022-06-23 19:07 UTC, merged